# Generated by Django 3.2.16 on 2022-10-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comm',
            old_name='article',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='comm',
            name='text',
            field=models.TextField(verbose_name='текст комментария'),
        ),
    ]
