# Generated by Django 3.2.16 on 2022-10-27 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20221025_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='comm',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comm',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comm',
            name='text',
            field=models.TextField(),
        ),
    ]
