# Generated by Django 3.2.16 on 2022-10-28 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20221027_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comm',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
    ]
