# Generated by Django 3.2.16 on 2022-11-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_delete_comm'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='edit_allow',
            field=models.BooleanField(default=True),
        ),
    ]
