# Generated by Django 3.2.16 on 2022-11-11 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_commentary_edit_allow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentary',
            name='edit_allow',
        ),
    ]
