# Generated by Django 3.2.16 on 2022-11-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_commentary_edit_allow'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
